# Generated by Django 4.2.6 on 2023-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_listing_description_listing_sold_listing_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="band",
            name="genre",
            field=models.CharField(
                choices=[
                    ("HH", "Hip Hop"),
                    ("DH", "Dancehall"),
                    ("PP", "Pop"),
                    ("JZ", "Jazz"),
                    ("AR", "Alternative Rock"),
                ],
                max_length=5,
            ),
        ),
    ]
